// Generated from the Polish texts (see logic/terms.ts): the same texts with the words of
// other disciplines (mata, kort, stół…), declined. Only texts that change are listed.
export const TERM_TEXTS: Record<string, Record<string, string>> = {
 "kort": {
  "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdego boiska wygenerują się same, znajdziesz je w zakładce „Klucze boisk”. Potem w panelu organizatora rozlosujesz zespoły do grup.": "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdego kortu wygenerują się same, znajdziesz je w zakładce „Klucze kortów”. Potem w panelu organizatora rozlosujesz zespoły do grup.",
  "Boiska": "Korty",
  "Boisko": "Kort",
  "Boisko {n}": "Kort {n}",
  "Do wydruku i przyklejenia przy boiskach: kod QR do panelu boiska i klucz.": "Do wydruku i przyklejenia przy kortach: kod QR do panelu kortu i klucz.",
  "Kartki dla boisk": "Kartki dla kortów",
  "Każda grupa gra na swoim boisku, mecz za meczem.": "Każda grupa gra na swoim korcie, mecz za meczem.",
  "Każde boisko ma swój klucz. Podaj go osobie, która liczy punkty na tym boisku. Z kluczem do boiska 3 można prowadzić tylko mecze na boisku 3. Zakończonego meczu nie zmieni nikt poza Tobą.": "Każdy kort ma swój klucz. Podaj go osobie, która liczy punkty na tym korcie. Z kluczem do kortu 3 można prowadzić tylko mecze na korcie 3. Zakończonego meczu nie zmieni nikt poza Tobą.",
  "Każdy mecz rozpocznie się 2 minuty po zakończeniu poprzedniego meczu na tym boisku.": "Każdy mecz rozpocznie się 2 minuty po zakończeniu poprzedniego meczu na tym korcie.",
  "Klucze boisk": "Klucze kortów",
  "Kolejne mecze na boisku ›": "Kolejne mecze na korcie ›",
  "Kolejne mecze na tym boisku": "Kolejne mecze na tym korcie",
  "Kolejny mecz na każdym boisku. Godzina zmienia się sama: 2 minuty po zakończeniu meczu, który trwa.": "Kolejny mecz na każdym korcie. Godzina zmienia się sama: 2 minuty po zakończeniu meczu, który trwa.",
  "Liczba boisk": "Liczba kortów",
  "Na telewizor lub rzutnik na hali: boiska, tabele i drabinki zmieniają się same.": "Na telewizor lub rzutnik na hali: korty, tabele i drabinki zmieniają się same.",
  "Na tym boisku nie ma już kolejnych meczów.": "Na tym korcie nie ma już kolejnych meczów.",
  "Na tym boisku nie ma już meczów.": "Na tym korcie nie ma już meczów.",
  "Na tym boisku nie ma już zaplanowanych meczów.": "Na tym korcie nie ma już zaplanowanych meczów.",
  "Na tym boisku nie ma meczów.": "Na tym korcie nie ma meczów.",
  "Następny mecz na tym boisku:": "Następny mecz na tym korcie:",
  "Obróć telefon poziomo, ustaw kamerę na boisko i naciśnij „Rozpocznij transmisję na żywo”.": "Obróć telefon poziomo, ustaw kamerę na kort i naciśnij „Rozpocznij transmisję na żywo”.",
  "Obróć telefon poziomo, ustaw kamerę na boisko i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.": "Obróć telefon poziomo, ustaw kamerę na kort i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.",
  "Osobna kamera na wybranych boiskach": "Osobna kamera na wybranych kortach",
  "Otwiera ten panel i wszystkie boiska. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów boisk się nie zmieniają. To nie jest hasło do konta.": "Otwiera ten panel i wszystkie korty. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów kortów się nie zmieniają. To nie jest hasło do konta.",
  "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na całe boisko.": "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na cały kort.",
  "Przesunięto {n} mecz na tym boisku.|Przesunięto {n} mecze na tym boisku.|Przesunięto {n} meczów na tym boisku.": "Przesunięto {n} mecz na tym korcie.|Przesunięto {n} mecze na tym korcie.|Przesunięto {n} meczów na tym korcie.",
  "Rozegrane na tym boisku": "Rozegrane na tym korcie",
  "Szukaj drużyny lub boiska": "Szukaj drużyny lub kortu",
  "Ten telefon jest zalogowany jako sędzia boiska {court}.": "Ten telefon jest zalogowany jako sędzia kortu {court}.",
  "To nie jest klucz do boiska {court}. Zapytaj sędziego głównego.": "To nie jest klucz do kortu {court}. Zapytaj sędziego głównego.",
  "Transmisja z boiska {n}": "Transmisja z kortu {n}",
  "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zespoły, losować grupy i poprawiać wyniki. Klucze dla sędziów boisk wygenerują się same.": "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zespoły, losować grupy i poprawiać wyniki. Klucze dla sędziów kortów wygenerują się same.",
  "W aplikacji wybierz boisko, na które patrzy kamera.": "W aplikacji wybierz kort, na który patrzy kamera.",
  "Wpisywanie i poprawianie wyników, klucze boisk, terminarz, drabinka, ustawienia punktacji.": "Wpisywanie i poprawianie wyników, klucze kortów, terminarz, drabinka, ustawienia punktacji.",
  "Wpisz drużynę albo numer boiska, Enter wybiera pierwszy mecz": "Wpisz drużynę albo numer kortu, Enter wybiera pierwszy mecz",
  "Wpisz tytuł, np. nazwę turnieju i boiska. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).": "Wpisz tytuł, np. nazwę turnieju i kortu. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).",
  "Wpisz zespoły każdej kategorii i rozlosuj je do grup. Losowanie rozdziela zespoły z tego samego klubu i od razu układa terminarz: start {start}, boisk: {courts}, mecz co {slot} min.": "Wpisz zespoły każdej kategorii i rozlosuj je do grup. Losowanie rozdziela zespoły z tego samego klubu i od razu układa terminarz: start {start}, kortów: {courts}, mecz co {slot} min.",
  "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy boisku) i naciśnij „Zapisz transmisję”.": "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy korcie) i naciśnij „Zapisz transmisję”.",
  "Wybierz boisko i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym boisku wisi też kartka z kodem QR, który prowadzi prosto do tego boiska.": "Wybierz kort i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym korcie wisi też kartka z kodem QR, który prowadzi prosto do tego kortu.",
  "Wybierz boisko, na które patrzy kamera. Gdy boisko jest jedno, aplikacja wybierze je sama.": "Wybierz kort, na który patrzy kamera. Gdy kort jest jeden, aplikacja wybierze go sama.",
  "Wymaga klucza boiska {n}": "Wymaga klucza kortu {n}",
  "Wytnij kartki i przyklej przy boiskach. Klucz możesz też zakleić i podać tylko sędziemu.": "Wytnij kartki i przyklej przy kortach. Klucz możesz też zakleić i podać tylko sędziemu.",
  "Zobacz boiska": "Zobacz korty",
  "boisko": "kort",
  "na każdym boisku (mecz + przerwa).": "na każdym korcie (mecz + przerwa).",
  "tablice wyników boisk": "tablice wyników kortów",
  "{label}: wpisz klucz boiska": "{label}: wpisz klucz kortu",
  "{n} boiska": "{n} korty",
  "· Boisko": "· Kort",
  "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tego boiska.": "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tego kortu.",
  "„Oznacz jako trwający”: na stronie pojawi się „Mecz trwa, wynik po meczu”. Przydaje się na boiskach, gdzie nikt nie liczy punktów na telefonie.": "„Oznacz jako trwający”: na stronie pojawi się „Mecz trwa, wynik po meczu”. Przydaje się na kortach, gdzie nikt nie liczy punktów na telefonie."
 },
 "stol": {
  "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdego boiska wygenerują się same, znajdziesz je w zakładce „Klucze boisk”. Potem w panelu organizatora rozlosujesz zespoły do grup.": "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdego stołu wygenerują się same, znajdziesz je w zakładce „Klucze stołów”. Potem w panelu organizatora rozlosujesz zespoły do grup.",
  "Boiska": "Stoły",
  "Boisko": "Stół",
  "Boisko {n}": "Stół {n}",
  "Do wydruku i przyklejenia przy boiskach: kod QR do panelu boiska i klucz.": "Do wydruku i przyklejenia przy stołach: kod QR do panelu stołu i klucz.",
  "Kartki dla boisk": "Kartki dla stołów",
  "Każda grupa gra na swoim boisku, mecz za meczem.": "Każda grupa gra przy swoim stole, mecz za meczem.",
  "Każde boisko ma swój klucz. Podaj go osobie, która liczy punkty na tym boisku. Z kluczem do boiska 3 można prowadzić tylko mecze na boisku 3. Zakończonego meczu nie zmieni nikt poza Tobą.": "Każdy stół ma swój klucz. Podaj go osobie, która liczy punkty przy tym stole. Z kluczem do stołu 3 można prowadzić tylko mecze przy stole 3. Zakończonego meczu nie zmieni nikt poza Tobą.",
  "Każdy mecz rozpocznie się 2 minuty po zakończeniu poprzedniego meczu na tym boisku.": "Każdy mecz rozpocznie się 2 minuty po zakończeniu poprzedniego meczu przy tym stole.",
  "Klucze boisk": "Klucze stołów",
  "Kolejne mecze na boisku ›": "Kolejne mecze przy stole ›",
  "Kolejne mecze na tym boisku": "Kolejne mecze przy tym stole",
  "Kolejny mecz na każdym boisku. Godzina zmienia się sama: 2 minuty po zakończeniu meczu, który trwa.": "Kolejny mecz przy każdym stole. Godzina zmienia się sama: 2 minuty po zakończeniu meczu, który trwa.",
  "Liczba boisk": "Liczba stołów",
  "Na telewizor lub rzutnik na hali: boiska, tabele i drabinki zmieniają się same.": "Na telewizor lub rzutnik na hali: stoły, tabele i drabinki zmieniają się same.",
  "Na tym boisku nie ma już kolejnych meczów.": "Przy tym stole nie ma już kolejnych meczów.",
  "Na tym boisku nie ma już meczów.": "Przy tym stole nie ma już meczów.",
  "Na tym boisku nie ma już zaplanowanych meczów.": "Przy tym stole nie ma już zaplanowanych meczów.",
  "Na tym boisku nie ma meczów.": "Przy tym stole nie ma meczów.",
  "Następny mecz na tym boisku:": "Następny mecz przy tym stole:",
  "Obróć telefon poziomo, ustaw kamerę na boisko i naciśnij „Rozpocznij transmisję na żywo”.": "Obróć telefon poziomo, ustaw kamerę na stół i naciśnij „Rozpocznij transmisję na żywo”.",
  "Obróć telefon poziomo, ustaw kamerę na boisko i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.": "Obróć telefon poziomo, ustaw kamerę na stół i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.",
  "Osobna kamera na wybranych boiskach": "Osobna kamera przy wybranych stołach",
  "Otwiera ten panel i wszystkie boiska. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów boisk się nie zmieniają. To nie jest hasło do konta.": "Otwiera ten panel i wszystkie stoły. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów stołów się nie zmieniają. To nie jest hasło do konta.",
  "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na całe boisko.": "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na cały stół.",
  "Przesunięto {n} mecz na tym boisku.|Przesunięto {n} mecze na tym boisku.|Przesunięto {n} meczów na tym boisku.": "Przesunięto {n} mecz przy tym stole.|Przesunięto {n} mecze przy tym stole.|Przesunięto {n} meczów przy tym stole.",
  "Rozegrane na tym boisku": "Rozegrane przy tym stole",
  "Szukaj drużyny lub boiska": "Szukaj drużyny lub stołu",
  "Ten telefon jest zalogowany jako sędzia boiska {court}.": "Ten telefon jest zalogowany jako sędzia stołu {court}.",
  "To nie jest klucz do boiska {court}. Zapytaj sędziego głównego.": "To nie jest klucz do stołu {court}. Zapytaj sędziego głównego.",
  "Transmisja z boiska {n}": "Transmisja ze stołu {n}",
  "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zespoły, losować grupy i poprawiać wyniki. Klucze dla sędziów boisk wygenerują się same.": "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zespoły, losować grupy i poprawiać wyniki. Klucze dla sędziów stołów wygenerują się same.",
  "W aplikacji wybierz boisko, na które patrzy kamera.": "W aplikacji wybierz stół, na który patrzy kamera.",
  "Wpisywanie i poprawianie wyników, klucze boisk, terminarz, drabinka, ustawienia punktacji.": "Wpisywanie i poprawianie wyników, klucze stołów, terminarz, drabinka, ustawienia punktacji.",
  "Wpisz drużynę albo numer boiska, Enter wybiera pierwszy mecz": "Wpisz drużynę albo numer stołu, Enter wybiera pierwszy mecz",
  "Wpisz tytuł, np. nazwę turnieju i boiska. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).": "Wpisz tytuł, np. nazwę turnieju i stołu. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).",
  "Wpisz zespoły każdej kategorii i rozlosuj je do grup. Losowanie rozdziela zespoły z tego samego klubu i od razu układa terminarz: start {start}, boisk: {courts}, mecz co {slot} min.": "Wpisz zespoły każdej kategorii i rozlosuj je do grup. Losowanie rozdziela zespoły z tego samego klubu i od razu układa terminarz: start {start}, stołów: {courts}, mecz co {slot} min.",
  "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy boisku) i naciśnij „Zapisz transmisję”.": "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy stole) i naciśnij „Zapisz transmisję”.",
  "Wybierz boisko i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym boisku wisi też kartka z kodem QR, który prowadzi prosto do tego boiska.": "Wybierz stół i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym stole wisi też kartka z kodem QR, który prowadzi prosto do tego stołu.",
  "Wybierz boisko, na które patrzy kamera. Gdy boisko jest jedno, aplikacja wybierze je sama.": "Wybierz stół, na który patrzy kamera. Gdy stół jest jeden, aplikacja wybierze go sama.",
  "Wymaga klucza boiska {n}": "Wymaga klucza stołu {n}",
  "Wytnij kartki i przyklej przy boiskach. Klucz możesz też zakleić i podać tylko sędziemu.": "Wytnij kartki i przyklej przy stołach. Klucz możesz też zakleić i podać tylko sędziemu.",
  "Zobacz boiska": "Zobacz stoły",
  "boisko": "stół",
  "na każdym boisku (mecz + przerwa).": "przy każdym stole (mecz + przerwa).",
  "tablice wyników boisk": "tablice wyników stołów",
  "{label}: wpisz klucz boiska": "{label}: wpisz klucz stołu",
  "{n} boiska": "{n} stoły",
  "· Boisko": "· Stół",
  "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tego boiska.": "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tego stołu.",
  "„Oznacz jako trwający”: na stronie pojawi się „Mecz trwa, wynik po meczu”. Przydaje się na boiskach, gdzie nikt nie liczy punktów na telefonie.": "„Oznacz jako trwający”: na stronie pojawi się „Mecz trwa, wynik po meczu”. Przydaje się przy stołach, gdzie nikt nie liczy punktów na telefonie."
 },
 "mata": {
  ": godzina ustawia się sama, gdy sędzia poda wynik. Godziny dalszych meczów są orientacyjne.": ": godzina ustawia się sama, gdy sędzia poda wynik. Godziny dalszych walk są orientacyjne.",
  "Anuluj mecz (wróć do 0:0)": "Anuluj walkę (wróć do 0:0)",
  "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdego boiska wygenerują się same, znajdziesz je w zakładce „Klucze boisk”. Potem w panelu organizatora rozlosujesz zespoły do grup.": "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdej maty wygenerują się same, znajdziesz je w zakładce „Klucze mat”. Potem w panelu organizatora rozlosujesz zawodników do grup.",
  "Boiska": "Maty",
  "Boisko": "Mata",
  "Boisko {n}": "Mata {n}",
  "Brak kolejnych meczów": "Brak kolejnych walk",
  "Brak kolejnych meczów.": "Brak kolejnych walk.",
  "Brak meczów": "Brak walk",
  "Brak meczów.": "Brak walk.",
  "Co ile minut mecze": "Co ile minut walki",
  "Cofnij wynik (mecz nierozegrany)": "Cofnij wynik (walka nierozegrana)",
  "Czekamy na wyniki poprzednich meczów": "Czekamy na wyniki poprzednich walk",
  "Czy na pewno anulować ten mecz? Wynik zniknie, a mecz wróci do stanu „nie rozpoczęty”. Będzie można zacząć go od nowa.": "Czy na pewno anulować tę walkę? Wynik zniknie, a walka wróci do stanu „nie rozpoczęta”. Będzie można zacząć ją od nowa.",
  "Czy na pewno chcesz poprawić wynik tego meczu?": "Czy na pewno chcesz poprawić wynik tej walki?",
  "Do wydruku i przyklejenia przy boiskach: kod QR do panelu boiska i klucz.": "Do wydruku i przyklejenia przy matach: kod QR do panelu maty i klucz.",
  "Drużyny z dalszych miejsc w grupach grają o miejsca {from}–{to}. Każda drużyna rozegra mecze o konkretne miejsce.": "Zawodnicy z dalszych miejsc w grupach walczą o miejsca {from}–{to}. Każdy stoczy walki o konkretne miejsce.",
  "Filmujesz dzieci? Uprzedź rodziców i zapisz w regulaminie turnieju, że mecze są transmitowane (RODO).": "Filmujesz dzieci? Uprzedź rodziców i zapisz w regulaminie turnieju, że walki są transmitowane (RODO).",
  "Godziny są przybliżone: mecz z przerwą trwa ok. {n} minut, więc kolejne godziny liczymy co {n} minut.": "Godziny są przybliżone: walka z przerwą trwa ok. {n} minut, więc kolejne godziny liczymy co {n} minut.",
  "Grupy, mecze i wyniki": "Grupy, walki i wyniki",
  "Jak nadawać mecz na żywo?": "Jak nadawać walkę na żywo?",
  "Jak nadawać mecz na żywo? Instrukcja krok po kroku": "Jak nadawać walkę na żywo? Instrukcja krok po kroku",
  "Jedną albo kilka. Będą wyróżnione w tabelach i meczach, a tu zobaczysz ich najbliższe mecze.": "Jedną albo kilka. Będą wyróżnione w tabelach i walkach, a tu zobaczysz ich najbliższe walki.",
  "Jeszcze nie ma zakończonych meczów. Wyniki pojawią się tu zaraz po każdym meczu.": "Jeszcze nie ma zakończonych walk. Wyniki pojawią się tu zaraz po każdej walce.",
  "Kartki dla boisk": "Kartki dla mat",
  "Każda grupa gra na swoim boisku, mecz za meczem.": "Każda grupa walczy na swojej macie, walka za walką.",
  "Każde boisko ma swój klucz. Podaj go osobie, która liczy punkty na tym boisku. Z kluczem do boiska 3 można prowadzić tylko mecze na boisku 3. Zakończonego meczu nie zmieni nikt poza Tobą.": "Każda mata ma swój klucz. Podaj go osobie, która liczy punkty na tej macie. Z kluczem do maty 3 można prowadzić tylko walki na macie 3. Zakończonej walki nie zmieni nikt poza Tobą.",
  "Każdy mecz rozpocznie się 2 minuty po zakończeniu poprzedniego meczu na tym boisku.": "Każda walka rozpocznie się 2 minuty po zakończeniu poprzedniej walki na tej macie.",
  "Kliknij mecz, żeby wpisać lub poprawić wynik.": "Kliknij walkę, żeby wpisać lub poprawić wynik.",
  "Klucze boisk": "Klucze mat",
  "Kolejne mecze na boisku ›": "Kolejne walki na macie ›",
  "Kolejne mecze na tym boisku": "Kolejne walki na tej macie",
  "Kolejność: punkty, różnica ({unit}), więcej zdobytych, bezpośredni mecz.": "Kolejność: punkty, różnica ({unit}), więcej zdobytych, bezpośrednia walka.",
  "Kolejność: punkty, stosunek setów, stosunek małych punktów, bezpośredni mecz.": "Kolejność: punkty, stosunek setów, stosunek małych punktów, bezpośrednia walka.",
  "Kolejny mecz na każdym boisku. Godzina zmienia się sama: 2 minuty po zakończeniu meczu, który trwa.": "Kolejna walka na każdej macie. Godzina zmienia się sama: 2 minuty po zakończeniu walki, która trwa.",
  "Koniec meczu": "Koniec walki",
  "Koniec meczu? Wynik": "Koniec walki? Wynik",
  "Liczba boisk": "Liczba mat",
  "M: mecze": "M: walki",
  "Mecz": "Walka",
  "Mecz jeszcze się nie zaczął.": "Walka jeszcze się nie zaczęła.",
  "Mecz nie jest jeszcze rozstrzygnięty, brakuje seta.": "Walka nie jest jeszcze rozstrzygnięta, brakuje seta.",
  "Mecz o {n}. miejsce": "Walka o {n}. miejsce",
  "Mecz rozstrzygnięty:": "Walka rozstrzygnięta:",
  "Mecz rozstrzygnął się po secie {n}, kolejne sety są zbędne.": "Walka rozstrzygnęła się po secie {n}, kolejne sety są zbędne.",
  "Mecz trwa": "Walka trwa",
  "Mecz trwa. Wynik pojawi się po meczu.": "Walka trwa. Wynik pojawi się po walce.",
  "Mecz trwa: godzinę następnego ustawisz po jego zakończeniu.": "Walka trwa: godzinę następnej ustawisz po jej zakończeniu.",
  "Mecz zakończony": "Walka zakończona",
  "Mecze": "Walki",
  "Mecze czekające na wynik: {n}. Kliknij mecz, wpisz sety z kartki i zapisz.": "Walki czekające na wynik: {n}. Kliknij walkę, wpisz sety z kartki i zapisz.",
  "Mecze grupy": "Walki grupy",
  "Mecze i poprawki": "Walki i poprawki",
  "Mecze o miejsca": "Walki o miejsca",
  "Mecze wkrótce": "Walki wkrótce",
  "Miejsca {from}–{to}, mecz {n}": "Miejsca {from}–{to}, walka {n}",
  "Minut od meczu do meczu": "Minut od walki do walki",
  "Możesz nadawać mecz na żywo z telefonu (Facebook albo YouTube) i pokazać obraz kibicom na stronie turnieju, obok wyników. Nie jest to obowiązkowe.": "Możesz nadawać walkę na żywo z telefonu (Facebook albo YouTube) i pokazać obraz kibicom na stronie turnieju, obok wyników. Nie jest to obowiązkowe.",
  "Na telewizor lub rzutnik na hali: boiska, tabele i drabinki zmieniają się same.": "Na telewizor lub rzutnik na hali: maty, tabele i drabinki zmieniają się same.",
  "Na tym boisku nie ma już kolejnych meczów.": "Na tej macie nie ma już kolejnych walk.",
  "Na tym boisku nie ma już meczów.": "Na tej macie nie ma już walk.",
  "Na tym boisku nie ma już zaplanowanych meczów.": "Na tej macie nie ma już zaplanowanych walk.",
  "Na tym boisku nie ma meczów.": "Na tej macie nie ma walk.",
  "Nadchodzące mecze": "Nadchodzące walki",
  "Najbliższy mecz": "Najbliższa walka",
  "Najbliższy mecz:": "Najbliższa walka:",
  "Następny mecz": "Następna walka",
  "Następny mecz na tym boisku:": "Następna walka na tej macie:",
  "Następny mecz o": "Następna walka o",
  "Następny mecz o {time}.": "Następna walka o {time}.",
  "Następny mecz zaczyna się 2 minuty po zakończeniu meczu, który trwa": "Następna walka zaczyna się 2 minuty po zakończeniu walki, która trwa",
  "Nie znaleziono meczu.": "Nie znaleziono walki.",
  "Obróć telefon poziomo, ustaw kamerę na boisko i naciśnij „Rozpocznij transmisję na żywo”.": "Obróć telefon poziomo, ustaw kamerę na matę i naciśnij „Rozpocznij transmisję na żywo”.",
  "Obróć telefon poziomo, ustaw kamerę na boisko i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.": "Obróć telefon poziomo, ustaw kamerę na matę i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.",
  "Odczyt meczów": "Odczyt walk",
  "Osobna kamera na wybranych boiskach": "Osobna kamera na wybranych matach",
  "Ostatni mecz grupowy:": "Ostatnia walka grupowa:",
  "Ostatnie mecze:": "Ostatnie walki:",
  "Otwiera ten panel i wszystkie boiska. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów boisk się nie zmieniają. To nie jest hasło do konta.": "Otwiera ten panel i wszystkie maty. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów mat się nie zmieniają. To nie jest hasło do konta.",
  "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na całe boisko.": "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na całą matę.",
  "Postaw telefon poziomo na statywie i zacznij transmisję. Wynik z panelu sędziego pojawia się na obrazie sam, a po meczu aplikacja przechodzi do następnego.": "Postaw telefon poziomo na statywie i zacznij transmisję. Wynik z panelu sędziego pojawia się na obrazie sam, a po walce aplikacja przechodzi do następnej.",
  "Przesunięto {n} mecz na tym boisku.|Przesunięto {n} mecze na tym boisku.|Przesunięto {n} meczów na tym boisku.": "Przesunięto {n} walkę na tej macie.|Przesunięto {n} walki na tej macie.|Przesunięto {n} walk na tej macie.",
  "Rozegrane mecze się nie zmieniają. Po {end} gry przechodzą na następny dzień od {start}.": "Stoczone walki się nie zmieniają. Po {end} walki przechodzą na następny dzień od {start}.",
  "Rozegrane na tym boisku": "Rozegrane na tej macie",
  "Rozpocznij mecz i licz: {unit}": "Rozpocznij walkę i licz: {unit}",
  "Szukaj drużyny lub boiska": "Szukaj zawodnika lub maty",
  "Sędzia główny oznaczył ten mecz jako trwający, bez liczenia wyniku na żywo.": "Sędzia główny oznaczył tę walkę jako trwającą, bez liczenia wyniku na żywo.",
  "Sędzia liczy punkty na stronie jak zwykle. Po sekundzie ten sam wynik jest na obrazie: drużyny, sety i punkty. Po meczu aplikacja sama przechodzi do następnego.": "Sędzia liczy punkty na stronie jak zwykle. Po sekundzie ten sam wynik jest na obrazie. Po walce aplikacja sama przechodzi do następnej.",
  "Tak będzie wyglądać faza pucharowa. Drużyny wpiszą się w drabinkę, gdy ich grupa rozegra wszystkie mecze; do tego czasu widać, które miejsce z której grupy gdzie trafi.": "Tak będzie wyglądać faza pucharowa. Zawodnicy wpiszą się w drabinkę, gdy ich grupa stoczy wszystkie walki; do tego czasu widać, które miejsce z której grupy gdzie trafi.",
  "Tak, anuluj mecz": "Tak, anuluj walkę",
  "Ten telefon jest zalogowany jako sędzia boiska {court}.": "Ten telefon jest zalogowany jako sędzia maty {court}.",
  "To nie jest klucz do boiska {court}. Zapytaj sędziego głównego.": "To nie jest klucz do maty {court}. Zapytaj sędziego głównego.",
  "Transmisja z boiska {n}": "Transmisja z maty {n}",
  "Tu możesz wyzerować wszystkie wyniki, np. po meczach próbnych. Grupy zostają, a godziny meczów wrócą do terminarza.": "Tu możesz wyzerować wszystkie wyniki, np. po walkach próbnych. Grupy zostają, a godziny walk wrócą do terminarza.",
  "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zespoły, losować grupy i poprawiać wyniki. Klucze dla sędziów boisk wygenerują się same.": "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zawodników, losować grupy i poprawiać wyniki. Klucze dla sędziów mat wygenerują się same.",
  "W aplikacji wybierz boisko, na które patrzy kamera.": "W aplikacji wybierz matę, na którą patrzy kamera.",
  "Wpisywanie i poprawianie wyników, klucze boisk, terminarz, drabinka, ustawienia punktacji.": "Wpisywanie i poprawianie wyników, klucze mat, terminarz, drabinka, ustawienia punktacji.",
  "Wpisz drużynę albo numer boiska, Enter wybiera pierwszy mecz": "Wpisz zawodnika albo numer maty, Enter wybiera pierwszą walkę",
  "Wpisz tytuł, np. nazwę turnieju i boiska. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).": "Wpisz tytuł, np. nazwę turnieju i maty. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).",
  "Wpisz wynik meczu.": "Wpisz wynik walki.",
  "Wpisz zespoły każdej kategorii i rozlosuj je do grup. Losowanie rozdziela zespoły z tego samego klubu i od razu układa terminarz: start {start}, boisk: {courts}, mecz co {slot} min.": "Wpisz zawodników każdej kategorii i rozlosuj ich do grup. Losowanie rozdziela zawodników z tego samego klubu i od razu układa terminarz: start {start}, mat: {courts}, walka co {slot} min.",
  "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy boisku) i naciśnij „Zapisz transmisję”.": "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy macie) i naciśnij „Zapisz transmisję”.",
  "Wszystkie mecze": "Wszystkie walki",
  "Wszystkie mecze z wynikami w pliku CSV, który otwiera się w Excelu.": "Wszystkie walki z wynikami w pliku CSV, który otwiera się w Excelu.",
  "Wybierz boisko i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym boisku wisi też kartka z kodem QR, który prowadzi prosto do tego boiska.": "Wybierz matę i wpisz klucz, który dostałeś od sędziego głównego. Przy każdej macie wisi też kartka z kodem QR, który prowadzi prosto do tej maty.",
  "Wybierz boisko, na które patrzy kamera. Gdy boisko jest jedno, aplikacja wybierze je sama.": "Wybierz matę, na którą patrzy kamera. Gdy mata jest jedna, aplikacja wybierze ją sama.",
  "Wymaga klucza boiska {n}": "Wymaga klucza maty {n}",
  "Wytnij kartki i przyklej przy boiskach. Klucz możesz też zakleić i podać tylko sędziemu.": "Wytnij kartki i przyklej przy matach. Klucz możesz też zakleić i podać tylko sędziemu.",
  "Wyzerować wszystkie wyniki (meczów: {n}) i przywrócić godziny z terminarza? Grupy zostaną.": "Wyzerować wszystkie wyniki (walk: {n}) i przywrócić godziny z terminarza? Grupy zostaną.",
  "Zakończ mecz i wyślij wynik": "Zakończ walkę i wyślij wynik",
  "Zapisano: mecz co {n} min. Ostatni mecz: {last}.": "Zapisano: walka co {n} min. Ostatnia walka: {last}.",
  "Zapisz i następny mecz": "Zapisz i następna walka",
  "Zasady meczu": "Zasady walki",
  "Zmiana godzin meczów (sędzia główny)": "Zmiana godzin walk (sędzia główny)",
  "Zmiana przelicza godziny wszystkich meczów, które się jeszcze nie zaczęły, od najbliższej rundy ({when}), która zostaje o swojej godzinie.": "Zmiana przelicza godziny wszystkich walk, które się jeszcze nie zaczęły, od najbliższej rundy ({when}), która zostaje o swojej godzinie.",
  "Zmiana przelicza godziny wszystkich meczów, które się jeszcze nie zaczęły.": "Zmiana przelicza godziny wszystkich walk, które się jeszcze nie zaczęły.",
  "Zobacz boiska": "Zobacz maty",
  "boisko": "mata",
  "grupy, mecze i wyniki na żywo:": "grupy, walki i wyniki na żywo:",
  "mecz co {n} minut": "walka co {n} minut",
  "mecz na żywo": "walka na żywo",
  "mecze w terminarzu": "walki w terminarzu",
  "na każdym boisku (mecz + przerwa).": "na każdej macie (walka + przerwa).",
  "następny mecz": "następna walka",
  "spotkanie": "walka",
  "tablice wyników boisk": "tablice wyników mat",
  "wygrane mecze": "wygrane walki",
  "wynik po meczu": "wynik po walce",
  "{label}: wpisz klucz boiska": "{label}: wpisz klucz maty",
  "{n} boiska": "{n} maty",
  "{n} mecz trwa teraz.|{n} mecze trwają teraz.|{n} meczów trwa teraz.": "{n} walka trwa teraz.|{n} walki trwają teraz.|{n} walk trwa teraz.",
  "· Boisko": "· Mata",
  "· mecz jeszcze nierozstrzygnięty": "· walka jeszcze nierozstrzygnięta",
  "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tego boiska.": "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tej maty.",
  "„Oznacz jako trwający”: na stronie pojawi się „Mecz trwa, wynik po meczu”. Przydaje się na boiskach, gdzie nikt nie liczy punktów na telefonie.": "„Oznacz jako trwający”: na stronie pojawi się „Walka trwa, wynik po walce”. Przydaje się na matach, gdzie nikt nie liczy punktów na telefonie.",
  "← Lista meczów": "← Lista walk",
  "← Wybierz inny mecz": "← Wybierz inną walkę",
  "★ Mecz Twojej drużyny": "★ Walka Twojego zawodnika"
 },
 "szachy": {
  ": godzina ustawia się sama, gdy sędzia poda wynik. Godziny dalszych meczów są orientacyjne.": ": godzina ustawia się sama, gdy sędzia poda wynik. Godziny dalszych partii są orientacyjne.",
  "Anuluj mecz (wróć do 0:0)": "Anuluj partię (wróć do 0:0)",
  "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdego boiska wygenerują się same, znajdziesz je w zakładce „Klucze boisk”. Potem w panelu organizatora rozlosujesz zespoły do grup.": "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdego stołu wygenerują się same, znajdziesz je w zakładce „Klucze stołów”. Potem w panelu organizatora rozlosujesz zawodników do grup.",
  "Boiska": "Stoły",
  "Boisko": "Stół",
  "Boisko {n}": "Stół {n}",
  "Brak kolejnych meczów": "Brak kolejnych partii",
  "Brak kolejnych meczów.": "Brak kolejnych partii.",
  "Brak meczów": "Brak partii",
  "Brak meczów.": "Brak partii.",
  "Co ile minut mecze": "Co ile minut partie",
  "Cofnij wynik (mecz nierozegrany)": "Cofnij wynik (partia nierozegrana)",
  "Czekamy na wyniki poprzednich meczów": "Czekamy na wyniki poprzednich partii",
  "Czy na pewno anulować ten mecz? Wynik zniknie, a mecz wróci do stanu „nie rozpoczęty”. Będzie można zacząć go od nowa.": "Czy na pewno anulować tę partię? Wynik zniknie, a partia wróci do stanu „nie rozpoczęta”. Będzie można zacząć ją od nowa.",
  "Czy na pewno chcesz poprawić wynik tego meczu?": "Czy na pewno chcesz poprawić wynik tej partii?",
  "Do wydruku i przyklejenia przy boiskach: kod QR do panelu boiska i klucz.": "Do wydruku i przyklejenia przy stołach: kod QR do panelu stołu i klucz.",
  "Drużyny z dalszych miejsc w grupach grają o miejsca {from}–{to}. Każda drużyna rozegra mecze o konkretne miejsce.": "Zawodnicy z dalszych miejsc w grupach grają o miejsca {from}–{to}. Każdy rozegra partie o konkretne miejsce.",
  "Filmujesz dzieci? Uprzedź rodziców i zapisz w regulaminie turnieju, że mecze są transmitowane (RODO).": "Filmujesz dzieci? Uprzedź rodziców i zapisz w regulaminie turnieju, że partie są transmitowane (RODO).",
  "Godziny są przybliżone: mecz z przerwą trwa ok. {n} minut, więc kolejne godziny liczymy co {n} minut.": "Godziny są przybliżone: partia z przerwą trwa ok. {n} minut, więc kolejne godziny liczymy co {n} minut.",
  "Grupy, mecze i wyniki": "Grupy, partie i wyniki",
  "Jak nadawać mecz na żywo?": "Jak nadawać partię na żywo?",
  "Jak nadawać mecz na żywo? Instrukcja krok po kroku": "Jak nadawać partię na żywo? Instrukcja krok po kroku",
  "Jedną albo kilka. Będą wyróżnione w tabelach i meczach, a tu zobaczysz ich najbliższe mecze.": "Jedną albo kilka. Będą wyróżnione w tabelach i partiach, a tu zobaczysz ich najbliższe partie.",
  "Jeszcze nie ma zakończonych meczów. Wyniki pojawią się tu zaraz po każdym meczu.": "Jeszcze nie ma zakończonych partii. Wyniki pojawią się tu zaraz po każdej partii.",
  "Kartki dla boisk": "Kartki dla stołów",
  "Każda grupa gra na swoim boisku, mecz za meczem.": "Każda grupa gra przy swoim stole, partia za partią.",
  "Każde boisko ma swój klucz. Podaj go osobie, która liczy punkty na tym boisku. Z kluczem do boiska 3 można prowadzić tylko mecze na boisku 3. Zakończonego meczu nie zmieni nikt poza Tobą.": "Każdy stół ma swój klucz. Podaj go osobie, która liczy punkty przy tym stole. Z kluczem do stołu 3 można prowadzić tylko partie przy stole 3. Zakończonej partii nie zmieni nikt poza Tobą.",
  "Każdy mecz rozpocznie się 2 minuty po zakończeniu poprzedniego meczu na tym boisku.": "Każda partia rozpocznie się 2 minuty po zakończeniu poprzedniej partii przy tym stole.",
  "Kliknij mecz, żeby wpisać lub poprawić wynik.": "Kliknij partię, żeby wpisać lub poprawić wynik.",
  "Klucze boisk": "Klucze stołów",
  "Kolejne mecze na boisku ›": "Kolejne partie przy stole ›",
  "Kolejne mecze na tym boisku": "Kolejne partie przy tym stole",
  "Kolejność: punkty, różnica ({unit}), więcej zdobytych, bezpośredni mecz.": "Kolejność: punkty, różnica ({unit}), więcej zdobytych, bezpośrednia partia.",
  "Kolejność: punkty, stosunek setów, stosunek małych punktów, bezpośredni mecz.": "Kolejność: punkty, stosunek setów, stosunek małych punktów, bezpośrednia partia.",
  "Kolejny mecz na każdym boisku. Godzina zmienia się sama: 2 minuty po zakończeniu meczu, który trwa.": "Kolejna partia przy każdym stole. Godzina zmienia się sama: 2 minuty po zakończeniu partii, która trwa.",
  "Koniec meczu": "Koniec partii",
  "Koniec meczu? Wynik": "Koniec partii? Wynik",
  "Liczba boisk": "Liczba stołów",
  "M: mecze": "M: partie",
  "Mecz": "Partia",
  "Mecz jeszcze się nie zaczął.": "Partia jeszcze się nie zaczęła.",
  "Mecz nie jest jeszcze rozstrzygnięty, brakuje seta.": "Partia nie jest jeszcze rozstrzygnięta, brakuje seta.",
  "Mecz o {n}. miejsce": "Partia o {n}. miejsce",
  "Mecz rozstrzygnięty:": "Partia rozstrzygnięta:",
  "Mecz rozstrzygnął się po secie {n}, kolejne sety są zbędne.": "Partia rozstrzygnęła się po secie {n}, kolejne sety są zbędne.",
  "Mecz trwa": "Partia trwa",
  "Mecz trwa. Wynik pojawi się po meczu.": "Partia trwa. Wynik pojawi się po partii.",
  "Mecz trwa: godzinę następnego ustawisz po jego zakończeniu.": "Partia trwa: godzinę następnej ustawisz po jej zakończeniu.",
  "Mecz zakończony": "Partia zakończona",
  "Mecze": "Partie",
  "Mecze czekające na wynik: {n}. Kliknij mecz, wpisz sety z kartki i zapisz.": "Partie czekające na wynik: {n}. Kliknij partię, wpisz sety z kartki i zapisz.",
  "Mecze grupy": "Partie grupy",
  "Mecze i poprawki": "Partie i poprawki",
  "Mecze o miejsca": "Partie o miejsca",
  "Mecze wkrótce": "Partie wkrótce",
  "Miejsca {from}–{to}, mecz {n}": "Miejsca {from}–{to}, partia {n}",
  "Minut od meczu do meczu": "Minut od partii do partii",
  "Możesz nadawać mecz na żywo z telefonu (Facebook albo YouTube) i pokazać obraz kibicom na stronie turnieju, obok wyników. Nie jest to obowiązkowe.": "Możesz nadawać partię na żywo z telefonu (Facebook albo YouTube) i pokazać obraz kibicom na stronie turnieju, obok wyników. Nie jest to obowiązkowe.",
  "Na telewizor lub rzutnik na hali: boiska, tabele i drabinki zmieniają się same.": "Na telewizor lub rzutnik na hali: stoły, tabele i drabinki zmieniają się same.",
  "Na tym boisku nie ma już kolejnych meczów.": "Przy tym stole nie ma już kolejnych partii.",
  "Na tym boisku nie ma już meczów.": "Przy tym stole nie ma już partii.",
  "Na tym boisku nie ma już zaplanowanych meczów.": "Przy tym stole nie ma już zaplanowanych partii.",
  "Na tym boisku nie ma meczów.": "Przy tym stole nie ma partii.",
  "Nadchodzące mecze": "Nadchodzące partie",
  "Najbliższy mecz": "Najbliższa partia",
  "Najbliższy mecz:": "Najbliższa partia:",
  "Następny mecz": "Następna partia",
  "Następny mecz na tym boisku:": "Następna partia przy tym stole:",
  "Następny mecz o": "Następna partia o",
  "Następny mecz o {time}.": "Następna partia o {time}.",
  "Następny mecz zaczyna się 2 minuty po zakończeniu meczu, który trwa": "Następna partia zaczyna się 2 minuty po zakończeniu partii, która trwa",
  "Nie znaleziono meczu.": "Nie znaleziono partii.",
  "Obróć telefon poziomo, ustaw kamerę na boisko i naciśnij „Rozpocznij transmisję na żywo”.": "Obróć telefon poziomo, ustaw kamerę na stół i naciśnij „Rozpocznij transmisję na żywo”.",
  "Obróć telefon poziomo, ustaw kamerę na boisko i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.": "Obróć telefon poziomo, ustaw kamerę na stół i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.",
  "Odczyt meczów": "Odczyt partii",
  "Osobna kamera na wybranych boiskach": "Osobna kamera przy wybranych stołach",
  "Ostatni mecz grupowy:": "Ostatnia partia grupowa:",
  "Ostatnie mecze:": "Ostatnie partie:",
  "Otwiera ten panel i wszystkie boiska. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów boisk się nie zmieniają. To nie jest hasło do konta.": "Otwiera ten panel i wszystkie stoły. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów stołów się nie zmieniają. To nie jest hasło do konta.",
  "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na całe boisko.": "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na całą stół.",
  "Postaw telefon poziomo na statywie i zacznij transmisję. Wynik z panelu sędziego pojawia się na obrazie sam, a po meczu aplikacja przechodzi do następnego.": "Postaw telefon poziomo na statywie i zacznij transmisję. Wynik z panelu sędziego pojawia się na obrazie sam, a po partii aplikacja przechodzi do następnej.",
  "Przesunięto {n} mecz na tym boisku.|Przesunięto {n} mecze na tym boisku.|Przesunięto {n} meczów na tym boisku.": "Przesunięto {n} partię przy tym stole.|Przesunięto {n} partie przy tym stole.|Przesunięto {n} partii przy tym stole.",
  "Rozegrane mecze się nie zmieniają. Po {end} gry przechodzą na następny dzień od {start}.": "Rozegrane partie się nie zmieniają. Po {end} partie przechodzą na następny dzień od {start}.",
  "Rozegrane na tym boisku": "Rozegrane przy tym stole",
  "Rozpocznij mecz i licz: {unit}": "Rozpocznij partię i licz: {unit}",
  "Szukaj drużyny lub boiska": "Szukaj zawodnika lub stołu",
  "Sędzia główny oznaczył ten mecz jako trwający, bez liczenia wyniku na żywo.": "Sędzia główny oznaczył tę partię jako trwającą, bez liczenia wyniku na żywo.",
  "Sędzia liczy punkty na stronie jak zwykle. Po sekundzie ten sam wynik jest na obrazie: drużyny, sety i punkty. Po meczu aplikacja sama przechodzi do następnego.": "Sędzia liczy punkty na stronie jak zwykle. Po sekundzie ten sam wynik jest na obrazie. Po partii aplikacja sama przechodzi do następnej.",
  "Tak będzie wyglądać faza pucharowa. Drużyny wpiszą się w drabinkę, gdy ich grupa rozegra wszystkie mecze; do tego czasu widać, które miejsce z której grupy gdzie trafi.": "Tak będzie wyglądać faza pucharowa. Zawodnicy wpiszą się w drabinkę, gdy ich grupa rozegra wszystkie partie; do tego czasu widać, które miejsce z której grupy gdzie trafi.",
  "Tak, anuluj mecz": "Tak, anuluj partię",
  "Ten telefon jest zalogowany jako sędzia boiska {court}.": "Ten telefon jest zalogowany jako sędzia stołu {court}.",
  "To nie jest klucz do boiska {court}. Zapytaj sędziego głównego.": "To nie jest klucz do stołu {court}. Zapytaj sędziego głównego.",
  "Transmisja z boiska {n}": "Transmisja ze stołu {n}",
  "Tu możesz wyzerować wszystkie wyniki, np. po meczach próbnych. Grupy zostają, a godziny meczów wrócą do terminarza.": "Tu możesz wyzerować wszystkie wyniki, np. po partiach próbnych. Grupy zostają, a godziny partii wrócą do terminarza.",
  "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zespoły, losować grupy i poprawiać wyniki. Klucze dla sędziów boisk wygenerują się same.": "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zawodników, losować grupy i poprawiać wyniki. Klucze dla sędziów stołów wygenerują się same.",
  "W aplikacji wybierz boisko, na które patrzy kamera.": "W aplikacji wybierz stół, na który patrzy kamera.",
  "Wpisywanie i poprawianie wyników, klucze boisk, terminarz, drabinka, ustawienia punktacji.": "Wpisywanie i poprawianie wyników, klucze stołów, terminarz, drabinka, ustawienia punktacji.",
  "Wpisz drużynę albo numer boiska, Enter wybiera pierwszy mecz": "Wpisz zawodnika albo numer stołu, Enter wybiera pierwszą partię",
  "Wpisz tytuł, np. nazwę turnieju i boiska. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).": "Wpisz tytuł, np. nazwę turnieju i stołu. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).",
  "Wpisz wynik meczu.": "Wpisz wynik partii.",
  "Wpisz zespoły każdej kategorii i rozlosuj je do grup. Losowanie rozdziela zespoły z tego samego klubu i od razu układa terminarz: start {start}, boisk: {courts}, mecz co {slot} min.": "Wpisz zawodników każdej kategorii i rozlosuj ich do grup. Losowanie rozdziela zawodników z tego samego klubu i od razu układa terminarz: start {start}, stołów: {courts}, partia co {slot} min.",
  "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy boisku) i naciśnij „Zapisz transmisję”.": "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy stole) i naciśnij „Zapisz transmisję”.",
  "Wszystkie mecze": "Wszystkie partie",
  "Wszystkie mecze z wynikami w pliku CSV, który otwiera się w Excelu.": "Wszystkie partie z wynikami w pliku CSV, który otwiera się w Excelu.",
  "Wybierz boisko i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym boisku wisi też kartka z kodem QR, który prowadzi prosto do tego boiska.": "Wybierz stół i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym stole wisi też kartka z kodem QR, który prowadzi prosto do tego stołu.",
  "Wybierz boisko, na które patrzy kamera. Gdy boisko jest jedno, aplikacja wybierze je sama.": "Wybierz stół, na który patrzy kamera. Gdy stół jest jeden, aplikacja wybierze go sama.",
  "Wymaga klucza boiska {n}": "Wymaga klucza stołu {n}",
  "Wytnij kartki i przyklej przy boiskach. Klucz możesz też zakleić i podać tylko sędziemu.": "Wytnij kartki i przyklej przy stołach. Klucz możesz też zakleić i podać tylko sędziemu.",
  "Wyzerować wszystkie wyniki (meczów: {n}) i przywrócić godziny z terminarza? Grupy zostaną.": "Wyzerować wszystkie wyniki (partii: {n}) i przywrócić godziny z terminarza? Grupy zostaną.",
  "Zakończ mecz i wyślij wynik": "Zakończ partię i wyślij wynik",
  "Zapisano: mecz co {n} min. Ostatni mecz: {last}.": "Zapisano: partia co {n} min. Ostatnia partia: {last}.",
  "Zapisz i następny mecz": "Zapisz i następna partia",
  "Zasady meczu": "Zasady partii",
  "Zmiana godzin meczów (sędzia główny)": "Zmiana godzin partii (sędzia główny)",
  "Zmiana przelicza godziny wszystkich meczów, które się jeszcze nie zaczęły, od najbliższej rundy ({when}), która zostaje o swojej godzinie.": "Zmiana przelicza godziny wszystkich partii, które się jeszcze nie zaczęły, od najbliższej rundy ({when}), która zostaje o swojej godzinie.",
  "Zmiana przelicza godziny wszystkich meczów, które się jeszcze nie zaczęły.": "Zmiana przelicza godziny wszystkich partii, które się jeszcze nie zaczęły.",
  "Zobacz boiska": "Zobacz stoły",
  "boisko": "stół",
  "grupy, mecze i wyniki na żywo:": "grupy, partie i wyniki na żywo:",
  "mecz co {n} minut": "partia co {n} minut",
  "mecz na żywo": "partia na żywo",
  "mecze w terminarzu": "partie w terminarzu",
  "na każdym boisku (mecz + przerwa).": "przy każdym stole (partia + przerwa).",
  "następny mecz": "następna partia",
  "spotkanie": "partia",
  "tablice wyników boisk": "tablice wyników stołów",
  "wygrane mecze": "wygrane partie",
  "wynik po meczu": "wynik po partii",
  "{label}: wpisz klucz boiska": "{label}: wpisz klucz stołu",
  "{n} boiska": "{n} stoły",
  "{n} mecz trwa teraz.|{n} mecze trwają teraz.|{n} meczów trwa teraz.": "{n} partia trwa teraz.|{n} partie trwają teraz.|{n} partii trwa teraz.",
  "· Boisko": "· Stół",
  "· mecz jeszcze nierozstrzygnięty": "· partia jeszcze nierozstrzygnięta",
  "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tego boiska.": "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tego stołu.",
  "„Oznacz jako trwający”: na stronie pojawi się „Mecz trwa, wynik po meczu”. Przydaje się na boiskach, gdzie nikt nie liczy punktów na telefonie.": "„Oznacz jako trwający”: na stronie pojawi się „Partia trwa, wynik po partii”. Przydaje się przy stołach, gdzie nikt nie liczy punktów na telefonie.",
  "← Lista meczów": "← Lista partii",
  "← Wybierz inny mecz": "← Wybierz inną partię",
  "★ Mecz Twojej drużyny": "★ Partia Twojego zawodnika"
 },
 "tarcza": {
  "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdego boiska wygenerują się same, znajdziesz je w zakładce „Klucze boisk”. Potem w panelu organizatora rozlosujesz zespoły do grup.": "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdej tarczy wygenerują się same, znajdziesz je w zakładce „Klucze tarcz”. Potem w panelu organizatora rozlosujesz zespoły do grup.",
  "Boiska": "Tarcze",
  "Boisko": "Tarcza",
  "Boisko {n}": "Tarcza {n}",
  "Do wydruku i przyklejenia przy boiskach: kod QR do panelu boiska i klucz.": "Do wydruku i przyklejenia przy tarczach: kod QR do panelu tarczy i klucz.",
  "Kartki dla boisk": "Kartki dla tarcz",
  "Każda grupa gra na swoim boisku, mecz za meczem.": "Każda grupa gra przy swojej tarczy, mecz za meczem.",
  "Każde boisko ma swój klucz. Podaj go osobie, która liczy punkty na tym boisku. Z kluczem do boiska 3 można prowadzić tylko mecze na boisku 3. Zakończonego meczu nie zmieni nikt poza Tobą.": "Każda tarcza ma swój klucz. Podaj go osobie, która liczy punkty przy tej tarczy. Z kluczem do tarczy 3 można prowadzić tylko mecze przy tarczy 3. Zakończonego meczu nie zmieni nikt poza Tobą.",
  "Każdy mecz rozpocznie się 2 minuty po zakończeniu poprzedniego meczu na tym boisku.": "Każdy mecz rozpocznie się 2 minuty po zakończeniu poprzedniego meczu przy tej tarczy.",
  "Klucze boisk": "Klucze tarcz",
  "Kolejne mecze na boisku ›": "Kolejne mecze przy tarczy ›",
  "Kolejne mecze na tym boisku": "Kolejne mecze przy tej tarczy",
  "Kolejny mecz na każdym boisku. Godzina zmienia się sama: 2 minuty po zakończeniu meczu, który trwa.": "Kolejny mecz przy każdej tarczy. Godzina zmienia się sama: 2 minuty po zakończeniu meczu, który trwa.",
  "Liczba boisk": "Liczba tarcz",
  "Na telewizor lub rzutnik na hali: boiska, tabele i drabinki zmieniają się same.": "Na telewizor lub rzutnik na hali: tarcze, tabele i drabinki zmieniają się same.",
  "Na tym boisku nie ma już kolejnych meczów.": "Przy tej tarczy nie ma już kolejnych meczów.",
  "Na tym boisku nie ma już meczów.": "Przy tej tarczy nie ma już meczów.",
  "Na tym boisku nie ma już zaplanowanych meczów.": "Przy tej tarczy nie ma już zaplanowanych meczów.",
  "Na tym boisku nie ma meczów.": "Przy tej tarczy nie ma meczów.",
  "Następny mecz na tym boisku:": "Następny mecz przy tej tarczy:",
  "Obróć telefon poziomo, ustaw kamerę na boisko i naciśnij „Rozpocznij transmisję na żywo”.": "Obróć telefon poziomo, ustaw kamerę na tarczę i naciśnij „Rozpocznij transmisję na żywo”.",
  "Obróć telefon poziomo, ustaw kamerę na boisko i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.": "Obróć telefon poziomo, ustaw kamerę na tarczę i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.",
  "Osobna kamera na wybranych boiskach": "Osobna kamera przy wybranych tarczach",
  "Otwiera ten panel i wszystkie boiska. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów boisk się nie zmieniają. To nie jest hasło do konta.": "Otwiera ten panel i wszystkie tarcze. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów tarcz się nie zmieniają. To nie jest hasło do konta.",
  "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na całe boisko.": "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na całą tarczę.",
  "Przesunięto {n} mecz na tym boisku.|Przesunięto {n} mecze na tym boisku.|Przesunięto {n} meczów na tym boisku.": "Przesunięto {n} mecz przy tej tarczy.|Przesunięto {n} mecze przy tej tarczy.|Przesunięto {n} meczów przy tej tarczy.",
  "Rozegrane na tym boisku": "Rozegrane przy tej tarczy",
  "Szukaj drużyny lub boiska": "Szukaj drużyny lub tarczy",
  "Ten telefon jest zalogowany jako sędzia boiska {court}.": "Ten telefon jest zalogowany jako sędzia tarczy {court}.",
  "To nie jest klucz do boiska {court}. Zapytaj sędziego głównego.": "To nie jest klucz do tarczy {court}. Zapytaj sędziego głównego.",
  "Transmisja z boiska {n}": "Transmisja z tarczy {n}",
  "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zespoły, losować grupy i poprawiać wyniki. Klucze dla sędziów boisk wygenerują się same.": "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zespoły, losować grupy i poprawiać wyniki. Klucze dla sędziów tarcz wygenerują się same.",
  "W aplikacji wybierz boisko, na które patrzy kamera.": "W aplikacji wybierz tarczę, na którą patrzy kamera.",
  "Wpisywanie i poprawianie wyników, klucze boisk, terminarz, drabinka, ustawienia punktacji.": "Wpisywanie i poprawianie wyników, klucze tarcz, terminarz, drabinka, ustawienia punktacji.",
  "Wpisz drużynę albo numer boiska, Enter wybiera pierwszy mecz": "Wpisz drużynę albo numer tarczy, Enter wybiera pierwszy mecz",
  "Wpisz tytuł, np. nazwę turnieju i boiska. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).": "Wpisz tytuł, np. nazwę turnieju i tarczy. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).",
  "Wpisz zespoły każdej kategorii i rozlosuj je do grup. Losowanie rozdziela zespoły z tego samego klubu i od razu układa terminarz: start {start}, boisk: {courts}, mecz co {slot} min.": "Wpisz zespoły każdej kategorii i rozlosuj je do grup. Losowanie rozdziela zespoły z tego samego klubu i od razu układa terminarz: start {start}, tarcz: {courts}, mecz co {slot} min.",
  "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy boisku) i naciśnij „Zapisz transmisję”.": "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy tarczy) i naciśnij „Zapisz transmisję”.",
  "Wybierz boisko i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym boisku wisi też kartka z kodem QR, który prowadzi prosto do tego boiska.": "Wybierz tarczę i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym tarczy wisi też kartka z kodem QR, który prowadzi prosto do tej tarczy.",
  "Wybierz boisko, na które patrzy kamera. Gdy boisko jest jedno, aplikacja wybierze je sama.": "Wybierz tarczę, na którą patrzy kamera. Gdy tarcza jest jedna, aplikacja wybierze ją sama.",
  "Wymaga klucza boiska {n}": "Wymaga klucza tarczy {n}",
  "Wytnij kartki i przyklej przy boiskach. Klucz możesz też zakleić i podać tylko sędziemu.": "Wytnij kartki i przyklej przy tarczach. Klucz możesz też zakleić i podać tylko sędziemu.",
  "Zobacz boiska": "Zobacz tarcze",
  "boisko": "tarcza",
  "na każdym boisku (mecz + przerwa).": "przy każdej tarczy (mecz + przerwa).",
  "tablice wyników boisk": "tablice wyników tarcz",
  "{label}: wpisz klucz boiska": "{label}: wpisz klucz tarczy",
  "{n} boiska": "{n} tarcze",
  "· Boisko": "· Tarcza",
  "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tego boiska.": "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tej tarczy.",
  "„Oznacz jako trwający”: na stronie pojawi się „Mecz trwa, wynik po meczu”. Przydaje się na boiskach, gdzie nikt nie liczy punktów na telefonie.": "„Oznacz jako trwający”: na stronie pojawi się „Mecz trwa, wynik po meczu”. Przydaje się przy tarczach, gdzie nikt nie liczy punktów na telefonie."
 },
 "basen": {
  "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdego boiska wygenerują się same, znajdziesz je w zakładce „Klucze boisk”. Potem w panelu organizatora rozlosujesz zespoły do grup.": "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdego basenu wygenerują się same, znajdziesz je w zakładce „Klucze basenów”. Potem w panelu organizatora rozlosujesz zespoły do grup.",
  "Boiska": "Baseny",
  "Boisko": "Basen",
  "Boisko {n}": "Basen {n}",
  "Do wydruku i przyklejenia przy boiskach: kod QR do panelu boiska i klucz.": "Do wydruku i przyklejenia przy basenach: kod QR do panelu basenu i klucz.",
  "Kartki dla boisk": "Kartki dla basenów",
  "Każda grupa gra na swoim boisku, mecz za meczem.": "Każda grupa gra w swoim basenie, mecz za meczem.",
  "Każde boisko ma swój klucz. Podaj go osobie, która liczy punkty na tym boisku. Z kluczem do boiska 3 można prowadzić tylko mecze na boisku 3. Zakończonego meczu nie zmieni nikt poza Tobą.": "Każdy basen ma swój klucz. Podaj go osobie, która liczy punkty w tym basenie. Z kluczem do basenu 3 można prowadzić tylko mecze w basenie 3. Zakończonego meczu nie zmieni nikt poza Tobą.",
  "Każdy mecz rozpocznie się 2 minuty po zakończeniu poprzedniego meczu na tym boisku.": "Każdy mecz rozpocznie się 2 minuty po zakończeniu poprzedniego meczu w tym basenie.",
  "Klucze boisk": "Klucze basenów",
  "Kolejne mecze na boisku ›": "Kolejne mecze w basenie ›",
  "Kolejne mecze na tym boisku": "Kolejne mecze w tym basenie",
  "Kolejny mecz na każdym boisku. Godzina zmienia się sama: 2 minuty po zakończeniu meczu, który trwa.": "Kolejny mecz w każdym basenie. Godzina zmienia się sama: 2 minuty po zakończeniu meczu, który trwa.",
  "Liczba boisk": "Liczba basenów",
  "Na telewizor lub rzutnik na hali: boiska, tabele i drabinki zmieniają się same.": "Na telewizor lub rzutnik na hali: baseny, tabele i drabinki zmieniają się same.",
  "Na tym boisku nie ma już kolejnych meczów.": "W tym basenie nie ma już kolejnych meczów.",
  "Na tym boisku nie ma już meczów.": "W tym basenie nie ma już meczów.",
  "Na tym boisku nie ma już zaplanowanych meczów.": "W tym basenie nie ma już zaplanowanych meczów.",
  "Na tym boisku nie ma meczów.": "W tym basenie nie ma meczów.",
  "Następny mecz na tym boisku:": "Następny mecz w tym basenie:",
  "Obróć telefon poziomo, ustaw kamerę na boisko i naciśnij „Rozpocznij transmisję na żywo”.": "Obróć telefon poziomo, ustaw kamerę na basen i naciśnij „Rozpocznij transmisję na żywo”.",
  "Obróć telefon poziomo, ustaw kamerę na boisko i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.": "Obróć telefon poziomo, ustaw kamerę na basen i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.",
  "Osobna kamera na wybranych boiskach": "Osobna kamera w wybranych basenach",
  "Otwiera ten panel i wszystkie boiska. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów boisk się nie zmieniają. To nie jest hasło do konta.": "Otwiera ten panel i wszystkie baseny. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów basenów się nie zmieniają. To nie jest hasło do konta.",
  "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na całe boisko.": "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na cały basen.",
  "Przesunięto {n} mecz na tym boisku.|Przesunięto {n} mecze na tym boisku.|Przesunięto {n} meczów na tym boisku.": "Przesunięto {n} mecz w tym basenie.|Przesunięto {n} mecze w tym basenie.|Przesunięto {n} meczów w tym basenie.",
  "Rozegrane na tym boisku": "Rozegrane w tym basenie",
  "Szukaj drużyny lub boiska": "Szukaj drużyny lub basenu",
  "Ten telefon jest zalogowany jako sędzia boiska {court}.": "Ten telefon jest zalogowany jako sędzia basenu {court}.",
  "To nie jest klucz do boiska {court}. Zapytaj sędziego głównego.": "To nie jest klucz do basenu {court}. Zapytaj sędziego głównego.",
  "Transmisja z boiska {n}": "Transmisja z basenu {n}",
  "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zespoły, losować grupy i poprawiać wyniki. Klucze dla sędziów boisk wygenerują się same.": "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zespoły, losować grupy i poprawiać wyniki. Klucze dla sędziów basenów wygenerują się same.",
  "W aplikacji wybierz boisko, na które patrzy kamera.": "W aplikacji wybierz basen, na który patrzy kamera.",
  "Wpisywanie i poprawianie wyników, klucze boisk, terminarz, drabinka, ustawienia punktacji.": "Wpisywanie i poprawianie wyników, klucze basenów, terminarz, drabinka, ustawienia punktacji.",
  "Wpisz drużynę albo numer boiska, Enter wybiera pierwszy mecz": "Wpisz drużynę albo numer basenu, Enter wybiera pierwszy mecz",
  "Wpisz tytuł, np. nazwę turnieju i boiska. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).": "Wpisz tytuł, np. nazwę turnieju i basenu. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).",
  "Wpisz zespoły każdej kategorii i rozlosuj je do grup. Losowanie rozdziela zespoły z tego samego klubu i od razu układa terminarz: start {start}, boisk: {courts}, mecz co {slot} min.": "Wpisz zespoły każdej kategorii i rozlosuj je do grup. Losowanie rozdziela zespoły z tego samego klubu i od razu układa terminarz: start {start}, basenów: {courts}, mecz co {slot} min.",
  "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy boisku) i naciśnij „Zapisz transmisję”.": "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy basenie) i naciśnij „Zapisz transmisję”.",
  "Wybierz boisko i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym boisku wisi też kartka z kodem QR, który prowadzi prosto do tego boiska.": "Wybierz basen i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym basenie wisi też kartka z kodem QR, który prowadzi prosto do tego basenu.",
  "Wybierz boisko, na które patrzy kamera. Gdy boisko jest jedno, aplikacja wybierze je sama.": "Wybierz basen, na który patrzy kamera. Gdy basen jest jeden, aplikacja wybierze go sama.",
  "Wymaga klucza boiska {n}": "Wymaga klucza basenu {n}",
  "Wytnij kartki i przyklej przy boiskach. Klucz możesz też zakleić i podać tylko sędziemu.": "Wytnij kartki i przyklej przy basenach. Klucz możesz też zakleić i podać tylko sędziemu.",
  "Zobacz boiska": "Zobacz baseny",
  "boisko": "basen",
  "na każdym boisku (mecz + przerwa).": "w każdym basenie (mecz + przerwa).",
  "tablice wyników boisk": "tablice wyników basenów",
  "{label}: wpisz klucz boiska": "{label}: wpisz klucz basenu",
  "{n} boiska": "{n} baseny",
  "· Boisko": "· Basen",
  "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tego boiska.": "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tego basenu.",
  "„Oznacz jako trwający”: na stronie pojawi się „Mecz trwa, wynik po meczu”. Przydaje się na boiskach, gdzie nikt nie liczy punktów na telefonie.": "„Oznacz jako trwający”: na stronie pojawi się „Mecz trwa, wynik po meczu”. Przydaje się w basenach, gdzie nikt nie liczy punktów na telefonie."
 },
 "lodowisko": {
  "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdego boiska wygenerują się same, znajdziesz je w zakładce „Klucze boisk”. Potem w panelu organizatora rozlosujesz zespoły do grup.": "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdego lodowiska wygenerują się same, znajdziesz je w zakładce „Klucze lodowisk”. Potem w panelu organizatora rozlosujesz zespoły do grup.",
  "Boiska": "Lodowiska",
  "Boisko": "Lodowisko",
  "Boisko {n}": "Lodowisko {n}",
  "Do wydruku i przyklejenia przy boiskach: kod QR do panelu boiska i klucz.": "Do wydruku i przyklejenia przy lodowiskach: kod QR do panelu lodowiska i klucz.",
  "Kartki dla boisk": "Kartki dla lodowisk",
  "Każda grupa gra na swoim boisku, mecz za meczem.": "Każda grupa gra na swoim lodowisku, mecz za meczem.",
  "Każde boisko ma swój klucz. Podaj go osobie, która liczy punkty na tym boisku. Z kluczem do boiska 3 można prowadzić tylko mecze na boisku 3. Zakończonego meczu nie zmieni nikt poza Tobą.": "Każde lodowisko ma swój klucz. Podaj go osobie, która liczy punkty na tym lodowisku. Z kluczem do lodowiska 3 można prowadzić tylko mecze na lodowisku 3. Zakończonego meczu nie zmieni nikt poza Tobą.",
  "Każdy mecz rozpocznie się 2 minuty po zakończeniu poprzedniego meczu na tym boisku.": "Każdy mecz rozpocznie się 2 minuty po zakończeniu poprzedniego meczu na tym lodowisku.",
  "Klucze boisk": "Klucze lodowisk",
  "Kolejne mecze na boisku ›": "Kolejne mecze na lodowisku ›",
  "Kolejne mecze na tym boisku": "Kolejne mecze na tym lodowisku",
  "Kolejny mecz na każdym boisku. Godzina zmienia się sama: 2 minuty po zakończeniu meczu, który trwa.": "Kolejny mecz na każdym lodowisku. Godzina zmienia się sama: 2 minuty po zakończeniu meczu, który trwa.",
  "Liczba boisk": "Liczba lodowisk",
  "Na telewizor lub rzutnik na hali: boiska, tabele i drabinki zmieniają się same.": "Na telewizor lub rzutnik na hali: lodowiska, tabele i drabinki zmieniają się same.",
  "Na tym boisku nie ma już kolejnych meczów.": "Na tym lodowisku nie ma już kolejnych meczów.",
  "Na tym boisku nie ma już meczów.": "Na tym lodowisku nie ma już meczów.",
  "Na tym boisku nie ma już zaplanowanych meczów.": "Na tym lodowisku nie ma już zaplanowanych meczów.",
  "Na tym boisku nie ma meczów.": "Na tym lodowisku nie ma meczów.",
  "Następny mecz na tym boisku:": "Następny mecz na tym lodowisku:",
  "Obróć telefon poziomo, ustaw kamerę na boisko i naciśnij „Rozpocznij transmisję na żywo”.": "Obróć telefon poziomo, ustaw kamerę na lodowisko i naciśnij „Rozpocznij transmisję na żywo”.",
  "Obróć telefon poziomo, ustaw kamerę na boisko i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.": "Obróć telefon poziomo, ustaw kamerę na lodowisko i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.",
  "Osobna kamera na wybranych boiskach": "Osobna kamera na wybranych lodowiskach",
  "Otwiera ten panel i wszystkie boiska. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów boisk się nie zmieniają. To nie jest hasło do konta.": "Otwiera ten panel i wszystkie lodowiska. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów lodowisk się nie zmieniają. To nie jest hasło do konta.",
  "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na całe boisko.": "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na całe lodowisko.",
  "Przesunięto {n} mecz na tym boisku.|Przesunięto {n} mecze na tym boisku.|Przesunięto {n} meczów na tym boisku.": "Przesunięto {n} mecz na tym lodowisku.|Przesunięto {n} mecze na tym lodowisku.|Przesunięto {n} meczów na tym lodowisku.",
  "Rozegrane na tym boisku": "Rozegrane na tym lodowisku",
  "Szukaj drużyny lub boiska": "Szukaj drużyny lub lodowiska",
  "Ten telefon jest zalogowany jako sędzia boiska {court}.": "Ten telefon jest zalogowany jako sędzia lodowiska {court}.",
  "To nie jest klucz do boiska {court}. Zapytaj sędziego głównego.": "To nie jest klucz do lodowiska {court}. Zapytaj sędziego głównego.",
  "Transmisja z boiska {n}": "Transmisja z lodowiska {n}",
  "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zespoły, losować grupy i poprawiać wyniki. Klucze dla sędziów boisk wygenerują się same.": "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zespoły, losować grupy i poprawiać wyniki. Klucze dla sędziów lodowisk wygenerują się same.",
  "W aplikacji wybierz boisko, na które patrzy kamera.": "W aplikacji wybierz lodowisko, na które patrzy kamera.",
  "Wpisywanie i poprawianie wyników, klucze boisk, terminarz, drabinka, ustawienia punktacji.": "Wpisywanie i poprawianie wyników, klucze lodowisk, terminarz, drabinka, ustawienia punktacji.",
  "Wpisz drużynę albo numer boiska, Enter wybiera pierwszy mecz": "Wpisz drużynę albo numer lodowiska, Enter wybiera pierwszy mecz",
  "Wpisz tytuł, np. nazwę turnieju i boiska. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).": "Wpisz tytuł, np. nazwę turnieju i lodowiska. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).",
  "Wpisz zespoły każdej kategorii i rozlosuj je do grup. Losowanie rozdziela zespoły z tego samego klubu i od razu układa terminarz: start {start}, boisk: {courts}, mecz co {slot} min.": "Wpisz zespoły każdej kategorii i rozlosuj je do grup. Losowanie rozdziela zespoły z tego samego klubu i od razu układa terminarz: start {start}, lodowisk: {courts}, mecz co {slot} min.",
  "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy boisku) i naciśnij „Zapisz transmisję”.": "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy lodowisku) i naciśnij „Zapisz transmisję”.",
  "Wybierz boisko i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym boisku wisi też kartka z kodem QR, który prowadzi prosto do tego boiska.": "Wybierz lodowisko i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym lodowisku wisi też kartka z kodem QR, który prowadzi prosto do tego lodowiska.",
  "Wybierz boisko, na które patrzy kamera. Gdy boisko jest jedno, aplikacja wybierze je sama.": "Wybierz lodowisko, na które patrzy kamera. Gdy lodowisko jest jedno, aplikacja wybierze je sama.",
  "Wymaga klucza boiska {n}": "Wymaga klucza lodowiska {n}",
  "Wytnij kartki i przyklej przy boiskach. Klucz możesz też zakleić i podać tylko sędziemu.": "Wytnij kartki i przyklej przy lodowiskach. Klucz możesz też zakleić i podać tylko sędziemu.",
  "Zobacz boiska": "Zobacz lodowiska",
  "boisko": "lodowisko",
  "na każdym boisku (mecz + przerwa).": "na każdym lodowisku (mecz + przerwa).",
  "tablice wyników boisk": "tablice wyników lodowisk",
  "{label}: wpisz klucz boiska": "{label}: wpisz klucz lodowiska",
  "{n} boiska": "{n} lodowiska",
  "· Boisko": "· Lodowisko",
  "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tego boiska.": "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tego lodowiska.",
  "„Oznacz jako trwający”: na stronie pojawi się „Mecz trwa, wynik po meczu”. Przydaje się na boiskach, gdzie nikt nie liczy punktów na telefonie.": "„Oznacz jako trwający”: na stronie pojawi się „Mecz trwa, wynik po meczu”. Przydaje się na lodowiskach, gdzie nikt nie liczy punktów na telefonie."
 },
 "stanowisko": {
  "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdego boiska wygenerują się same, znajdziesz je w zakładce „Klucze boisk”. Potem w panelu organizatora rozlosujesz zespoły do grup.": "Baza jest pusta. Ustaw PIN sędziego głównego. Klucze dla każdego stanowiska wygenerują się same, znajdziesz je w zakładce „Klucze stanowisk”. Potem w panelu organizatora rozlosujesz zespoły do grup.",
  "Boiska": "Stanowiska",
  "Boisko": "Stanowisko",
  "Boisko {n}": "Stanowisko {n}",
  "Do wydruku i przyklejenia przy boiskach: kod QR do panelu boiska i klucz.": "Do wydruku i przyklejenia przy stanowiskach: kod QR do panelu stanowiska i klucz.",
  "Kartki dla boisk": "Kartki dla stanowisk",
  "Każda grupa gra na swoim boisku, mecz za meczem.": "Każda grupa gra na swoim stanowisku, mecz za meczem.",
  "Każde boisko ma swój klucz. Podaj go osobie, która liczy punkty na tym boisku. Z kluczem do boiska 3 można prowadzić tylko mecze na boisku 3. Zakończonego meczu nie zmieni nikt poza Tobą.": "Każde stanowisko ma swój klucz. Podaj go osobie, która liczy punkty na tym stanowisku. Z kluczem do stanowiska 3 można prowadzić tylko mecze na stanowisku 3. Zakończonego meczu nie zmieni nikt poza Tobą.",
  "Każdy mecz rozpocznie się 2 minuty po zakończeniu poprzedniego meczu na tym boisku.": "Każdy mecz rozpocznie się 2 minuty po zakończeniu poprzedniego meczu na tym stanowisku.",
  "Klucze boisk": "Klucze stanowisk",
  "Kolejne mecze na boisku ›": "Kolejne mecze na stanowisku ›",
  "Kolejne mecze na tym boisku": "Kolejne mecze na tym stanowisku",
  "Kolejny mecz na każdym boisku. Godzina zmienia się sama: 2 minuty po zakończeniu meczu, który trwa.": "Kolejny mecz na każdym stanowisku. Godzina zmienia się sama: 2 minuty po zakończeniu meczu, który trwa.",
  "Liczba boisk": "Liczba stanowisk",
  "Na telewizor lub rzutnik na hali: boiska, tabele i drabinki zmieniają się same.": "Na telewizor lub rzutnik na hali: stanowiska, tabele i drabinki zmieniają się same.",
  "Na tym boisku nie ma już kolejnych meczów.": "Na tym stanowisku nie ma już kolejnych meczów.",
  "Na tym boisku nie ma już meczów.": "Na tym stanowisku nie ma już meczów.",
  "Na tym boisku nie ma już zaplanowanych meczów.": "Na tym stanowisku nie ma już zaplanowanych meczów.",
  "Na tym boisku nie ma meczów.": "Na tym stanowisku nie ma meczów.",
  "Następny mecz na tym boisku:": "Następny mecz na tym stanowisku:",
  "Obróć telefon poziomo, ustaw kamerę na boisko i naciśnij „Rozpocznij transmisję na żywo”.": "Obróć telefon poziomo, ustaw kamerę na stanowisko i naciśnij „Rozpocznij transmisję na żywo”.",
  "Obróć telefon poziomo, ustaw kamerę na boisko i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.": "Obróć telefon poziomo, ustaw kamerę na stanowisko i w Larixie naciśnij duży czerwony przycisk. Po kilku sekundach obraz pojawi się w YouTube Studio.",
  "Osobna kamera na wybranych boiskach": "Osobna kamera na wybranych stanowiskach",
  "Otwiera ten panel i wszystkie boiska. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów boisk się nie zmieniają. To nie jest hasło do konta.": "Otwiera ten panel i wszystkie stanowiska. Po zmianie stary PIN przestaje działać na wszystkich telefonach. Klucze sędziów stanowisk się nie zmieniają. To nie jest hasło do konta.",
  "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na całe boisko.": "Postaw telefon na statywie albo oprzyj stabilnie, wysoko, z widokiem na całe stanowisko.",
  "Przesunięto {n} mecz na tym boisku.|Przesunięto {n} mecze na tym boisku.|Przesunięto {n} meczów na tym boisku.": "Przesunięto {n} mecz na tym stanowisku.|Przesunięto {n} mecze na tym stanowisku.|Przesunięto {n} meczów na tym stanowisku.",
  "Rozegrane na tym boisku": "Rozegrane na tym stanowisku",
  "Szukaj drużyny lub boiska": "Szukaj drużyny lub stanowiska",
  "Ten telefon jest zalogowany jako sędzia boiska {court}.": "Ten telefon jest zalogowany jako sędzia stanowiska {court}.",
  "To nie jest klucz do boiska {court}. Zapytaj sędziego głównego.": "To nie jest klucz do stanowiska {court}. Zapytaj sędziego głównego.",
  "Transmisja z boiska {n}": "Transmisja ze stanowiska {n}",
  "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zespoły, losować grupy i poprawiać wyniki. Klucze dla sędziów boisk wygenerują się same.": "Ustaw PIN (co najmniej 4 cyfry) i zapisz go. Tylko nim można wpisywać zespoły, losować grupy i poprawiać wyniki. Klucze dla sędziów stanowisk wygenerują się same.",
  "W aplikacji wybierz boisko, na które patrzy kamera.": "W aplikacji wybierz stanowisko, na które patrzy kamera.",
  "Wpisywanie i poprawianie wyników, klucze boisk, terminarz, drabinka, ustawienia punktacji.": "Wpisywanie i poprawianie wyników, klucze stanowisk, terminarz, drabinka, ustawienia punktacji.",
  "Wpisz drużynę albo numer boiska, Enter wybiera pierwszy mecz": "Wpisz drużynę albo numer stanowiska, Enter wybiera pierwszy mecz",
  "Wpisz tytuł, np. nazwę turnieju i boiska. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).": "Wpisz tytuł, np. nazwę turnieju i stanowiska. Widoczność: „Publiczny” albo „Niepubliczny” (niepubliczny też działa na naszej stronie, a nie pojawia się w wyszukiwarce).",
  "Wpisz zespoły każdej kategorii i rozlosuj je do grup. Losowanie rozdziela zespoły z tego samego klubu i od razu układa terminarz: start {start}, boisk: {courts}, mecz co {slot} min.": "Wpisz zespoły każdej kategorii i rozlosuj je do grup. Losowanie rozdziela zespoły z tego samego klubu i od razu układa terminarz: start {start}, stanowisk: {courts}, mecz co {slot} min.",
  "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy boisku) i naciśnij „Zapisz transmisję”.": "Wróć do tej strony, wklej link w pole „Link do transmisji całego turnieju” (albo przy stanowisku) i naciśnij „Zapisz transmisję”.",
  "Wybierz boisko i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym boisku wisi też kartka z kodem QR, który prowadzi prosto do tego boiska.": "Wybierz stanowisko i wpisz klucz, który dostałeś od sędziego głównego. Przy każdym stanowisku wisi też kartka z kodem QR, który prowadzi prosto do tego stanowiska.",
  "Wybierz boisko, na które patrzy kamera. Gdy boisko jest jedno, aplikacja wybierze je sama.": "Wybierz stanowisko, na które patrzy kamera. Gdy stanowisko jest jedno, aplikacja wybierze je sama.",
  "Wymaga klucza boiska {n}": "Wymaga klucza stanowiska {n}",
  "Wytnij kartki i przyklej przy boiskach. Klucz możesz też zakleić i podać tylko sędziemu.": "Wytnij kartki i przyklej przy stanowiskach. Klucz możesz też zakleić i podać tylko sędziemu.",
  "Zobacz boiska": "Zobacz stanowiska",
  "boisko": "stanowisko",
  "na każdym boisku (mecz + przerwa).": "na każdym stanowisku (mecz + przerwa).",
  "tablice wyników boisk": "tablice wyników stanowisk",
  "{label}: wpisz klucz boiska": "{label}: wpisz klucz stanowiska",
  "{n} boiska": "{n} stanowiska",
  "· Boisko": "· Stanowisko",
  "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tego boiska.": "„Nowy klucz” wylogowuje telefon, który używał starego klucza do tego stanowiska.",
  "„Oznacz jako trwający”: na stronie pojawi się „Mecz trwa, wynik po meczu”. Przydaje się na boiskach, gdzie nikt nie liczy punktów na telefonie.": "„Oznacz jako trwający”: na stronie pojawi się „Mecz trwa, wynik po meczu”. Przydaje się na stanowiskach, gdzie nikt nie liczy punktów na telefonie."
 }
}
